# Site settings
title: Zino Kader
subtitle: by HTML5 UP
email: zino@zinokader.se
description: I don't really need this site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address:
city: Stockholm
state:
zip_code: 16247
country: Sweden
phone: 072 250 0070

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/ZinoKader/
gitlab_url:
googleplus_url: https://plus.google.com/112232561067289599259
instagram_url:
linkedin_url: https://linkedin.com/in/zinokader/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/zinokader

# Build settings
markdown: kramdown

sass:
  style: compressed
